import axios from "axios";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import TanstackProvider from "./providers/TanstackProvider";
import ProtectedRoute from "./providers/ProtectedRoute";
import SidebarLayoutProvider from "./providers/DashboardLayoutProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProtectedRoute>
            <TanstackProvider>
              <SidebarLayoutProvider>
                {children}
                </SidebarLayoutProvider>
            </TanstackProvider>
          </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
